### ISSUE TITLE
Email upon STARQL AUDIT Test Case failure

### ISSUE THREAD

**Issue by hitormiss** [avb100/starrez-google-scripts#4]
Re: the StarQL Audit feature, it would be great if the Google Script could send *one* email alerting you that that one or more Test Cases failed when the Audit was run. You could specify an 'emailOnFailure' parameter in the Options object to provide an email address.  Thanks!

**Comment by bernot-dev** [comment]
Resolved in 62ef3b6.

New user property `EMAIL` must be configured. However, this can be done on the friendly configuration page of the *new* web app! In Scripts (from the Publish menu), choose Deploy as Web App..., then deploy and visit the the Web App URL. Also, I explicitly restricted the oAuth scopes required, so it won't ask for all-inclusive access to all of your e-mail. Just permission to send.

To use the audit failure e-mail, just add an `email` property to the options object and set the value to `true`.

```javascript
function runAudit() {
  var options = {
    "email": true,
    "spreadsheetId": "SPREADSHEET_ID_HERE",
    "testCases": [
      {
        "name": "Testing Users with Active Bookings",
        "query": "SELECT EntryID, ID1, NameFirst, NameLast, TermSession, RoomSpace, RoomType, EntryStatusEnum.Description AS BookingStatus \
                  FROM Booking \
                    LEFT JOIN Entry \
                    LEFT JOIN EntryStatusEnum \
                  WHERE Booking.EntryStatusEnum<>Cancelled \
                    AND Entry.Testing=True \
                    AND RoomSpaceID<>0"
      },
      {
        "name": "Untagged Transactions Created Before Yesterday",
        "query": "SELECT TransactionID, ID1, NameLast, NameFirst, TermSession, ChargeGroup, ChargeItem, Description, Amount, TransactionDate, SecurityUser.FullName AS CreatedBy \
                  FROM Transaction \
                    LEFT JOIN Entry \
                    LEFT JOIN SecurityUser \
                  WHERE Testing=False \
                    AND TransactionDate < ADD(Date,-1,days) \
                    AND TagFinance=0"
      }
    ]
  };
  audit(options);
}
```

The e-mail is pretty basic, but it includes a link to the Google Sheet with the audit results. Enjoy!
