### ISSUE TITLE
noRecordsMessage option not working

### ISSUE THREAD

**Issue by hitormiss** [avb100/starrez-google-scripts#5]
The  **noRecordsMessage** option was not working for me.  The Spreadsheet tab would update, leaving Row 2 blank below the frozen Row 1 and cell A2 would be left empty (i.e. neither my custom nor the default message would appear).

I altered line 116 of Reports.gs to add parentheses around the calculation of frozenRows+1  

> sheet.getRange(**\(**frozenRows+1**\)**,1).setValue(errorMessage);

That seemed to do the trick and now the custom message is showing up when I run my update function.

**Comment by bernot-dev** [comment]
I haven't been able to reproduce this issue in my latest version, but I was actively developing around this component yesterday. You may have gotten a bad commit.

Best I can figure, the extra parentheses shouldn't make a difference there, and adding them fails the [no-extra-parens rule](https://eslint.org/docs/rules/no-extra-parens) in ESLint.

**Comment by hitormiss** [comment]
Seems to be working for me now, so maybe it was a bad commit. Thanks!
