### ISSUE TITLE
Add setup script

### ISSUE THREAD

**Issue by bernot-dev** [avb100/starrez-google-scripts#6]
Use web app to setup values instead of relying on monkeying with values in code.

**Comment by bernot-dev** [comment]
Resolved.

**Comment by hitormiss** [comment]
I've set up a new Google Scripts project with your most recent version (i.e. with the setup script run as a web app).  After deploying as a web app and visiting the URL, I keep getting the error message "SyntaxError: Invalid quantifier ?." I double checked that I've copied over all the .js files correctly.  Any ideas why I'd be getting these errors?

![goggles scripts web app error when trying to configure](https://user-images.githubusercontent.com/3300893/40858906-e8ea08e0-65ad-11e8-9325-3061fce31165.png)

**Comment by bernot-dev** [comment]
I'm not getting that error from a clean install using `npm run setup`. However, it is related to a malformed regular expression.

I only use a few question marks in the whole script, so it's easy enough to check that. These ones should be okay:

In `GoogleDocs/report.gs:36-38`
```javascript
var errorMessage = typeof options.noRecordsMessage === "string"
        ? options.noRecordsMessage
        : "There aren't any records to display";
```

In `starrez.gs:273`
```javascript
roomLocationRegExp = "(?:\\b)(" + matches.join("|") + ")(?:\\b)";
```

There are a few approaches to figuring this out.

*If you have just been copy/pasting source, this is the one:*

**Option 1: Manually Debug in Google Apps Script**
If you have question marks anywhere else in the script (especially inside a regular expression), those would be likely suspects for the source of this bug. You can Find (Ctrl+F) in Google Apps Script and it will show you all instances.

*If you installed using the latest directions and the automatic setup script, you can try either of these, as well.*

**Option 2: Debug Local Copy with Help From ESLint**
A malformed regular expression can be caught by eslint. If you ran the latest setup script you can try `./node_modules/.bin/clasp pull` then `npm run lint` from the command line, and it should tell you exactly where the issue is.

**Option 3: Just Fix It**
Or just `npm run update` to not worry about where the error is and overwrite all the script files with the latest version. Unless the bug is in your `triggerable.gs` file, this should squash it. You will lose any modifications you have made to the script with this method.

**Comment by hitormiss** [comment]
D'oh!  I was using the "Google Apps Script GitHub Assistant" extension on Chrome and it was copying over the Setup/setup.js script.  When I finally got npm running on the command line and followed your set up instructions, I realized that script is not copied over to the Google Scripts project.  Once I deleted that file, I was able to run the Web App and configure.  Thanks for your help!
